steps:
  # Set up buildx
  - name: "gcr.io/cloud-builders/docker"
    args: ["buildx", "create", "--name", "mybuilder"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["buildx", "use", "mybuilder"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["buildx", "inspect", "--bootstrap"]

  # Build for both AMD64 and ARM64
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "buildx"
      - "build"
      - "--platform=linux/amd64,linux/arm64"
      - "-t"
      - "gcr.io/$PROJECT_ID/agentd-webtop:latest"
      - "-t"
      - "gcr.io/$PROJECT_ID/agentd-webtop:${SHORT_SHA}"
      - "-f"
      - "Dockerfile"
      - "--push"
      - "."

  # Verify the pushed images using docker buildx
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker buildx imagetools inspect gcr.io/$PROJECT_ID/agentd-webtop:latest
        docker buildx imagetools inspect gcr.io/$PROJECT_ID/agentd-webtop:${SHORT_SHA}

  # Verify the pushed images using Google Cloud SDK
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud container images describe gcr.io/$PROJECT_ID/agentd-webtop:latest
        gcloud container images describe gcr.io/$PROJECT_ID/agentd-webtop:${SHORT_SHA}

  # Add a delay to ensure GCR has fully processed the new images
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Waiting for images to be fully processed..."
        sleep 30

images:
  - "gcr.io/$PROJECT_ID/agentd-webtop:latest"
  - "gcr.io/$PROJECT_ID/agentd-webtop:${SHORT_SHA}"

timeout: "3600s"

options:
  machineType: "N1_HIGHCPU_8"
