steps:
  # Set up buildx
  - name: "gcr.io/cloud-builders/docker"
    args: ["buildx", "create", "--name", "mybuilder", "--use"]

  # Build for AMD64
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "buildx"
      - "build"
      - "--platform=linux/amd64"
      - "-t"
      - "gcr.io/$PROJECT_ID/agentd-webtop:latest-amd64"
      - "-t"
      - "gcr.io/$PROJECT_ID/agentd-webtop:${SHORT_SHA}-amd64"
      - "-f"
      - "Dockerfile"
      - "--push"
      - "."

  # Build for ARM64
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "buildx"
      - "build"
      - "--platform=linux/arm64"
      - "-t"
      - "gcr.io/$PROJECT_ID/agentd-webtop:latest-arm64"
      - "-t"
      - "gcr.io/$PROJECT_ID/agentd-webtop:${SHORT_SHA}-arm64"
      - "-f"
      - "Dockerfile"
      - "--push"
      - "."

  # Verify individual architecture images
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Verifying AMD64 image:"
        docker buildx imagetools inspect gcr.io/$PROJECT_ID/agentd-webtop:latest-amd64
        echo "Verifying ARM64 image:"
        docker buildx imagetools inspect gcr.io/$PROJECT_ID/agentd-webtop:latest-arm64

  # Create and push multi-arch manifest
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Creating multi-arch manifest for latest tag"
        docker manifest create gcr.io/$PROJECT_ID/agentd-webtop:latest \
          gcr.io/$PROJECT_ID/agentd-webtop:latest-amd64 \
          gcr.io/$PROJECT_ID/agentd-webtop:latest-arm64
        echo "Pushing multi-arch manifest for latest tag"
        docker manifest push gcr.io/$PROJECT_ID/agentd-webtop:latest

        echo "Creating multi-arch manifest for SHORT_SHA tag"
        docker manifest create gcr.io/$PROJECT_ID/agentd-webtop:${SHORT_SHA} \
          gcr.io/$PROJECT_ID/agentd-webtop:${SHORT_SHA}-amd64 \
          gcr.io/$PROJECT_ID/agentd-webtop:${SHORT_SHA}-arm64
        echo "Pushing multi-arch manifest for SHORT_SHA tag"
        docker manifest push gcr.io/$PROJECT_ID/agentd-webtop:${SHORT_SHA}

  # Verify the final multi-arch images
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        echo "Verifying final multi-arch image for latest tag:"
        docker buildx imagetools inspect gcr.io/$PROJECT_ID/agentd-webtop:latest
        echo "Verifying final multi-arch image for SHORT_SHA tag:"
        docker buildx imagetools inspect gcr.io/$PROJECT_ID/agentd-webtop:${SHORT_SHA}

images:
  - "gcr.io/$PROJECT_ID/agentd-webtop:latest"
  - "gcr.io/$PROJECT_ID/agentd-webtop:latest-amd64"
  - "gcr.io/$PROJECT_ID/agentd-webtop:latest-arm64"
  - "gcr.io/$PROJECT_ID/agentd-webtop:${SHORT_SHA}"
  - "gcr.io/$PROJECT_ID/agentd-webtop:${SHORT_SHA}-amd64"
  - "gcr.io/$PROJECT_ID/agentd-webtop:${SHORT_SHA}-arm64"

timeout: "3600s"

options:
  machineType: "N1_HIGHCPU_8"
