steps:
  # Set up QEMU for multi-architecture support
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

  # Set up Docker Buildx
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap

  # Build and push for multiple architectures
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t us-docker.pkg.dev/$PROJECT_ID/agentd/desktop-webtop:latest \
          -t us-docker.pkg.dev/$PROJECT_ID/agentd/desktop-webtop:${SHORT_SHA} \
          --push \
          .

  # Verify the multi-arch image
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker buildx imagetools inspect us-docker.pkg.dev/$PROJECT_ID/agentd/desktop-webtop:latest
        docker buildx imagetools inspect us-docker.pkg.dev/$PROJECT_ID/agentd/desktop-webtop:${SHORT_SHA}

images:
  - "us-docker.pkg.dev/$PROJECT_ID/agentd/desktop-webtop:latest"
  - "us-docker.pkg.dev/$PROJECT_ID/agentd/desktop-webtop:${SHORT_SHA}"

timeout: "3600s"

options:
  machineType: "N1_HIGHCPU_8"
