FROM lscr.io/linuxserver/webtop:arm64v8-latest

COPY . /config/agentd/

# Update and install dependencies
RUN apk update && \
    apk add --no-cache python3 py3-pip build-base libffi-dev openssl-dev curl

# Install Poetry using the official installation script
RUN curl -sSL https://install.python-poetry.org | python3 -

# Add Poetry to the PATH environment variable
ENV PATH="/config/.local/bin:$PATH"

RUN cd /config/agentd && poetry install

RUN mkdir -p /etc/services.d/uvicorn
COPY uvicorn-run.sh /etc/services.d/uvicorn/run
RUN chmod +x /etc/services.d/uvicorn/run