FROM lscr.io/linuxserver/webtop:latest

COPY . /config/agentd/

# Update and install dependencies
RUN apk update && \
    apk add --no-cache python3 py3-pip build-base libffi-dev openssl-dev curl poetry

RUN ls /config/agentd

RUN cd /config/agentd && poetry install

RUN mkdir -p /etc/services.d/uvicorn
COPY uvicorn-run.sh /etc/services.d/uvicorn/run
RUN chmod +x /etc/services.d/uvicorn/run