version: 1
disable_existing_loggers: False

formatters:
  custom:
    format: "[uvicorn] %(asctime)s %(levelname)s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: custom
    stream: ext://sys.stdout

loggers:
  uvicorn:
    level: DEBUG
    handlers: [console]
    propagate: no
  uvicorn.error:
    level: DEBUG
    handlers: [console]
    propagate: no
  uvicorn.access:
    level: DEBUG
    handlers: [console]
    propagate: no