#!/usr/bin/env bash
set -e
echo "Test log message from redis_run script" >&2


# Log the environment variables
env > /config/app/logs/redis_env.log

# exec a shell to Run Redis and pipe to sed to hack a prefix
exec sh -c "redis-server \
  --bind 0.0.0.0 \
  --maxmemory ${MAXMEMORY:-512mb} \
  --maxmemory-policy allkeys-lru \
  --loglevel ${LOG_LEVEL:-debug} \
  2>&1 | sed 's/^/[redis] /'"