#!/usr/bin/env bash
set -e

# Log the environment variables
env > /config/app/logs/uvicorn_env.log

cd /config/app

source ./pyenv_setup.sh
source ./venv/bin/activate

export DISPLAY=:1

exec uvicorn agentd.server:app --host 0.0.0.0 --port 8000
