#!/usr/bin/env bash
set -e

echo "Test log message from uvicorn_run script" >&2

cd /config/app

chown -R abc:abc /config/app

source ./pyenv_setup.sh
source ./venv/bin/activate

export DISPLAY=:1

exec s6-setuidgid abc uvicorn agentd.server:app \
    --host 0.0.0.0 --port 8000 --log-level debug \
    --log-format "[uvicorn] %(levelname)s %(message)s"